### ISSUE TITLE
(Restored issue) Perk duplication when dragging back to the pool (1.0.0.1)

### ISSUE THREAD

**Issue by KumoKairo** [KumoKairo/all_perks_streak_helper#1]
One person reported an issue where dragging a perk back from the killer duplicates it in the perks pool
Can't reproduce on my machine / build

**Comment by ComfyAntero** [comment]
I can duplicate perks in a two different ways: 
1)  Click on the perk in the pool with left or right mouse button (or even mouse scroll wheel)
2)  Click and drag a perk to the perk pool with right or left mouse button (or even mouse scroll wheel)

Closing the program does not fix the issue.

Reproduced on Windows.
